# -*- coding: utf-8 -*-
# """Fase1R.ipynb
# 
# Automatically generated by Colaboratory.
# 
# 
# # Seja ensinável e execute as tarefas compartilhadas. Por fins didáticos e para melhor separação mental das sintaxes Python/R, realizaremos todos os exercícios de Python em R.
# ![alt text](https://media.giphy.com/media/d3mlE7uhX8KFgEmY/200.gif)
# 
# Crie um algoritmo em R que mostre a mensagem "Alo mundo" na tela.
# """

# INSIRA SEU CÓDIGO AQUI
print('Alo Mundo!')

#"""Crie um algoritmo em R que peça dois números e imprima a soma."""

# INSIRA SEU CÓDIGO AQUI
print("Me dê dois números e irei fazer a soma deles.")
num1 <- as.integer(readline("Número 1: "))
num2 <- as.integer(readline("Número 2: "))
soma = num1 + num2

paste("Soma de", num1,"+",num2,"é igual a:",soma,"." )

#"""Crie um algoritmo em R que peça um número e então mostre a mensagem O número informado foi [número]."""

# INSIRA SEU CÓDIGO AQUI
num1 <- as.integer(readline("Por favor, insira um número: "))
paste("O número informado foi ", num1)

#"""Crie um algoritmo em R que converta metros para centímetros."""

# INSIRA SEU CÓDIGO AQUI
print("Me dê um número em metros e eu irei convertê-lo para centímetros.")
num1 <- as.double(readline("Número: "))
calc <- num1 * 100

paste("O valor",num1," metros em centímetros é",calc,".")

#"""Crie um algoritmo em Python que peça as 4 notas bimestrais e mostre a média."""

# INSIRA SEU CÓDIGO AQUI
print("Por favor, insira suas 4 notas bimestrais e irei calcular a sua média.")
lista <- vector()

for (c in 1:4){
  number = as.character(c)
  num = as.integer(readline(paste("Número", number ,":")))
  lista[c] <- num
}
media = mean(lista)

paste("Sua média é de:", media)

#"""Crie um algoritmo em R que peça o raio de um círculo, calcule e mostre sua área."""

# INSIRA SEU CÓDIGO AQUI
print("Me dê o raio de um círculo e eu irei calcular a área dele.")
raio = as.double(readline("Raio: "))
area = 3.14 * (raio ** 2)

paste("A área de um círculo com raio de",raio,"é de:",area,"em metros.")

#"""Crie um algoritmo em R que calcule a área de um quadrado, em seguida mostre o dobro desta área para o usuário."""

# INSIRA SEU CÓDIGO AQUI
print("Me dê um lado de um quadrado e eu irei calcular a área dele.")
lado = as.integer(readline("Lado: "))
area = lado * lado

paste("A área de um quadrado com o lado de",lado,"é de:",area,".")

#"""Crie um algoritmo em R que pergunte quanto você ganha por hora e o número de horas trabalhadas no mês. Calcule e mostre o total do seu salário no referido mês."""

# INSIRA SEU CÓDIGO AQUI
print("Me informe quanto você ganha por hora e quantas horas você trabalha ao mês e irei mostrar o total do seu salário por mês.")
ganha_hora = as.double(readline("Valor hora: "))
qtd_hora = as.integer(readline("Quantidade hora: "))
calc = ganha_hora*qtd_hora
paste("Você ganha R$",round(ganha_hora, digits = 2),"por hora e trabalha",qtd_hora,"horas por mês, logo seu salário é de R$",calc,".")

#"""Crie um algoritmo em R que peça a temperatura em graus Farenheit, transforme e mostre a temperatura em graus Celsius.
#C = (5 * (F-32) / 9).
#"""

# INSIRA SEU CÓDIGO AQUI
temperatura = as.integer(readline("Graus em Farenheit: "))
calc = (5*(temperatura-32)/9)
paste("A temperatura",temperatura,"°F em °C é ",round(calc,2))

#"""Crie um algoritmo em R que peça a temperatura em graus Celsius, transforme e mostre em graus Farenheit."""

# INSIRA SEU CÓDIGO AQUI
temperatura = as.integer(readline("Graus em Celcius: "))
calc = temperatura * 1.8 + 32
paste("A temperatura",temperatura,"°C em °F é",round(calc,2))

# """Crie um algoritmo em R que peça 2 números inteiros e um número real. Calcule e mostre:
# * a soma do dobro do primeiro com metade do segundo .
# * a soma do triplo do primeiro com o terceiro.
# * o terceiro elevado ao cubo.
# """

# INSIRA SEU CÓDIGO AQUI
print("Me dê dois números inteiros e um número real.")
num1 = as.integer(readline("Número 1 inteiro: "))
num2 = as.integer(readline("Número 2 inteiro: "))
num3 = as.double(readline("Número 1 real: "))

calc1 = (num1 * 2) + (num2 / 2)
calc2 = (num1 * 3) + num3
calc3 = num3 ** 3

paste("* a soma do dobro do primeiro com metade do segundo ",calc1,"
* a soma do triplo do primeiro com o terceiro.",calc2,"
* o terceiro elevado ao cubo",calc3,"")