# -*- coding: utf-8 -*-
"""Condicionais.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YfUiGLffZxql2x7rtefbnoYJuDmwYSvs

# **If**
"""

x = -10
if x > 0:
	print('Número positivo')
else:
	print('Número negativo')

"""# **Conectivos Lógicos**
![alt text](http://uploaddeimagens.com.br/images/002/157/511/full/conectivos-logicos.jpg?1561550251)
"""

x = "janeiro"
if x == 'janeiro' or x == 'fevereiro' or x == 'março':
	print('Trimestre 1')
elif x == 'abril' or x == 'maio' or x == 'junho':
	print('Trimestre 2')
else:
	print('Trimestre 3')

"""## **>>> Exercícios**


1.   Crie um algoritmo que solicite do usuário um número e calcule se ele é POSITIVO ou NEGATIVO (fácil)
2.   Crie um algoritmo que solicite peso e altura e como resultado printe o IMC na tela (médio)
3.   Crie um algoritmo que solicite do usuário um número e printe na tela PAR, quando número par e IMPAR, quando número ímpar(difícil)
"""

#1 
num = int(input("Digite um número: "))
if num > 0:
  print("O seu número é positivo")
else:
  print("O seu número é negativo")

#2
print("Olá, tudo bem? vamos calcular o seu IMC e ver como esta sua saúde?")
peso = float(input("Qual o seu peso?: "))
altura = float(input("Qual a sua altura?: "))

calculo = peso / (altura * altura)

if calculo > 18.50 and calculo < 24.99:
  print("o seu peso está normal, parabéns! IMC de {}".format(calculo))
elif calculo > 25 and calculo < 29.99:
  print("Você esta acima do peso, cuidado! IMC de {}".format(calculo))
elif calculo > 30 and calculo < 34.99:
  print("Você esta na faixa de obesidade I, procure um médico, IMC de {}".format(calculo))
elif calculo > 35 and calculo < 39.99:
  print("Você esta na faixa de obesidade II(severa), procure um médico, IMC de {}".format(calculo))
elif calculo > 40:
  print("Você esta na faixa de obesidade III(mórbida), procure um médico, IMC de {}".format(calculo))
else: 
  print("Insira um valor válido.")

#3
print("Vamos fazer uma brincadeira, você insere um número e eu digo se ele é par ou ímpar?")
num = int(input("número: "))

if num % 2 == 0:
  print("Número par!")
else:
  print("Número Ímpar!")