# -*- coding: utf-8 -*-
"""Fase1.ipynb

Automatically generated by Colaboratory.



Crie um algoritmo em Python que mostre a mensagem "Alo mundo" na tela.
"""

# INSIRA SEU CÓDIGO AQUI
print("Alo mundo!")

"""Crie um algoritmo em Python que peça dois números e imprima a soma."""

# INSIRA SEU CÓDIGO AQUI
print("Olá! me dê dois números e eu irei fazer a soma deles!")
num = int(input("Número: "))
num2 = int(input("Número: "))
soma = num + num2
print(f"O resultado de {num} + {num2} = {soma}")

"""Crie um algoritmo em Python que peça um número e então mostre a mensagem O número informado foi [número]."""

# INSIRA SEU CÓDIGO AQUI
num = int(input("Insira um número inteiro: "))
print(f"O número informado foi {num}")

"""Crie um algoritmo em Python que converta metros para centímetros."""

# INSIRA SEU CÓDIGO AQUI
num = float(input("Insira um número em metros que irei convertê-lo para centímetros! : "))
conversao = num * 100
print(f"O valor {num} em centímetros é {conversao}")

"""Crie um algoritmo em Python que peça as 4 notas bimestrais e mostre a média."""

# INSIRA SEU CÓDIGO AQUI
print("Insira quatro notas bimestrais e eu irei mostrar o valor da sua média!")
num1 = float(input("Nota 1: "))
num2 = float(input("Nota 2: "))
num3 = float(input("Nota 3: "))
num4 = float(input("Nota 4: "))

media = (num1+ num2+ num3+ num4) / 4

print(f"""____________________
Nota 1: {num1} 
Nota 2: {num2}
Nota 3: {num3}
Nota 4: {num4}
O valor da média é {media}
___________________""")

"""Crie um algoritmo em Python que peça o raio de um círculo, calcule e mostre sua área."""

# INSIRA SEU CÓDIGO AQUI
raio = float(input("Insira raio de um círculo: "))

area = 3.14 * (raio ** 2)

print(f"O valor da área do círculo é {area}")

"""Crie um algoritmo em Python que calcule a área de um quadrado, em seguida mostre o dobro desta área para o usuário."""

# INSIRA SEU CÓDIGO AQUI
alt = float(input("Qual a altura do seu quadrado?"))
lar = float(input("Qual a largura do seu quadrado? "))
area = alt * lar

print(f"A área do seu quadrado é de {area}")

"""Crie um algoritmo em Python que pergunte quanto você ganha por hora e o número de horas trabalhadas no mês. Calcule e mostre o total do seu salário no referido mês."""

# INSIRA SEU CÓDIGO AQUI
salario = float(input("Quanto voc^e ganha por hora?"))
num_horas = int(input("Quantas horas você trabalha por mês?"))
total = salario * num_horas

print(f"Se voce trabalha {num_horas} horas com R${salario} por hora, seu salário é de {total} ")

"""Crie um algoritmo em Python que peça a temperatura em graus Farenheit, transforme e mostre a temperatura em graus Celsius.
C = (5 * (F-32) / 9).
"""

# INSIRA SEU CÓDIGO AQUI
temp_f = float(input("Qual a temperatura em Farenheit?"))
temp_c = (5 * (temp_f-32) / 9)
print(f"A temperatura {temp_f} em celsius é {round(temp_c, 2)}")

"""Crie um algoritmo em Python que peça a temperatura em graus Celsius, transforme e mostre em graus Farenheit."""

# INSIRA SEU CÓDIGO AQUI
temp_c = float(input("Qual a temperatura em Celcius?"))
temp_f = (temp_c * 9/5) + 32
print(f"A temperatura {temp_c} e farenheit é {round(temp_f, 2)}")

"""Crie um algoritmo em Python que peça 2 números inteiros e um número real. Calcule e mostre:
* a soma do dobro do primeiro com metade do segundo .
* a soma do triplo do primeiro com o terceiro.
* o terceiro elevado ao cubo.
"""

# INSIRA SEU CÓDIGO AQUI
print("Me dê dois números inteiros e um número real.")
num1 = int(input("Numero inteiro 1: "))
num2 = int(input("Numero inteiro 2: "))
num3 = float(input("Numero real: "))

calc1 = (num1 + num1) + (num2/ 2)
calc2 =  (num1 * 3) + num3
calc3 = (num3 ** 3)

print(f"""a soma do dobro do primeiro com metade do segundo é igual a {calc1}.
a soma do triplo do primeiro com o terceiro. {calc2}
o terceiro elevado ao cubo {calc3}.""")
