# -*- coding: utf-8 -*-
"""Sets.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ppXe-sRzvbQsE4mES-OhlvIibaM8M3Xm

# **Sets(conjuntos**)

---

Tipo de dado iterável, imutável e sem elementos duplicados. Chamado de conjunto por possuir a mesma notação matemática dos conjuntos.
"""

x = {1,2,3,4,5}
print(type(x))

# Método add()
x.add(6)
print(x)

# Método union()
y = {"um","dois","três","quatro","cinco"}
z = y.union(x)
print(z)

# ou use "|"
z = y|x
print(z)

# Método difference() retorna a diferença entre as variáveis
z = x.difference(y)
print(z)

# Possível também subtrair e chegar ao mesmo resultado
z = x - y
print(z)

dir(set)

help(set)

"""# **Frozen Set**

---

"Conjuntos congelados" são objetos imutáveis que suportam métodos/operadores que não alterem os conjuntos a qual são aplicados.
"""

frozen = frozenset(["a","b","c"])
print(frozen)

dir(frozenset)

"""# **Exercícios**

---

1. Crie um algoritmo que pede ao usuário para digitar 3 números, diferentes entre sí, um de cada vez. A cada input do usuário insira o input dentro de um set e ao término printe na tela o output de seu set.
"""

# Insira seu código aqui
x = int(input("Quantos itens você deseja adicionar no seu conjunto?"))
c = 0
conjunto = set()
while c < x:
  item = input("Item: ")
  if item.isnumeric():
    item = int(item)
  conjunto.add(item)
  c = c + 1

print(conjunto)

"""2. Crie um algoritmo que receba 3 números como input do usuário e a seguir adicione-o dentro de um frozenset. Ao término, aplique algum atributo frozenset e printe na tela. Utilize dir(frozenset) para selecionar o atributo."""

# Insira seu código aqui
qtd = 3
c = 0 
conjunto = set()
frozen = frozenset (conjunto)
while c < qtd:
  c = c + 1 
  algo = input("Algo a adicionar: ")
  conjunto.add(algo)

print(frozen, conjunto)