# -*- coding: utf-8 -*-
"""Strings.ipynb

Automatically generated by Colaboratory.



# **Strings**
---
"""

nome = "Weber"
print(type(nome))

# F STRING
print(f"Oi, eu sou o {nome}")

# Formatando com F STRING
x = 1.61803399
print(f"O número de ouro é {x:.2f}")

# CONCATENAÇÃO 
a = "chat"
b = "bot"
print(a+b)

# ATRIBUIÇÃO DE NOVAS STRINGS
c = "ro"
print(c+b)

# SLICING/FATIAMENTO
frase = "Esta é uma string"
print(frase[0])

# string[começo:fim:passos]
print(frase[::2])

# ATRIBUTOS DO OBJETO str (https://docs.python.org/3/contents.html)
dir(str)

nome = 'Hello, my name is Maiyuri'

print(nome.split(maxsplit=1))

# Help!
help(str)

"""# **>>> Exercícios**
---

1.   Crie um algoritmo que solicite o nome do usuário e printe na sequência: "Bem vindo(a), <nome do usuário>" (fácil)
"""

# Insira seu código aqui
nome = str(input("Olá, tudo bem? como é o seu nome? "))
print(f"Bem vindo(a), {nome}")

"""2.   Crie um algoritmo que solicite do usuário nome e idade, printando na tela as informações organizadas em 1 frase. (médio)"""

# Insira seu código aqui
nome = str(input("Olá, qual o seu nome?"))
idade = int(input("Qual a sua idade?"))
while idade < 0:
  if idade < 0:
    print("uai, entao tu nem nasceu")
    idade = int(input("Qual a sua idade?"))
  else:
    print(f"O seu nome é {nome} e você tem {idade} anos.")

"""3.   Crie um algoritmo que solicite uma palavra e verifique se é um palíndromo, printando na tela o resultado (difícil)"""

# Insira seu código aqui
palavra = str(input("Por favor, insira uma palavra para o programa verificar se é palíndromo. "))

palindromo = palavra[::-1]

if palavra == palindromo:
  print("É palíndromo!")
else:
  print("Não é palíndromo!")

"""## **>>> Solução**

---

Visualize a solução abaixo
"""

# Exercício 1
nome = input("Qual é o seu nome?")
print(f"Bem vindo(a), {nome}")

# Exercício 2
nome = input("Qual seu nome?")
idade = input("Quantos anos você tem?")
print(f"Olá, {nome}! Que maravilha, tens {idade} anos e isto é ótimo!")

# Exercício 3
x = input("Digite 1 palavra:")
if x == x[::-1]:
  print("Palíndromo!")
else:
  print("Não é palíndromo!")
