# -*- coding: utf-8 -*-
"""Fase1_b1nlSNW.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18nrr1d5TCPf4yrlKbamiusvP7XlXvaC4

# Exercício exemplo
<b>Identificando conjuntos de dados</b><br>
Em uma pesquisa recente, foi perguntado a 614 proprietários de pequenas empresas nos Estados Unidos se eles achavam que a presença
de sua empresa no Facebook tinha valor. Duzentos e cinquenta e oito
dos 614 responderam que sim. Identifique a população e a amostra.
Descreva o conjunto de dados da amostra. (Adaptado de: Manta.)
<br><br>
<b>Solução</b><br>
A população consiste nas respostas de todos os proprietários de pequenas empresas dos Estados Unidos, e a amostra consiste nas respostas dos 614 pequenos empresários pesquisados. O conjunto de dados da amostra consiste
em 258 proprietários que responderam sim e 356 que responderam não

# Sua vez!
O departamento de energia dos Estados Unidos conduz pesquisas
semanais em aproximadamente 800 postos de gasolina para determinar
o preço médio por galão de gasolina comum. Em 10 de dezembro de
2012, o preço médio era US$ 3,35 por galão. Identifique a população
e a amostra. Descreva o conjunto de dados da amostra. (Fonte: Energy
Information Administration.)

* a. Identifique a população e a amostra.
* b. No que consiste o conjunto de dados da amostra?

**Sua resposta aqui!**

**a - A população seria todos postos de energia dos Estados Unidos e a amostra é a base de pesquisa ou seja, os 800 postos. A base consiste no valor do galão de gasolina, onde a média dos 800 postos pesquisados é de US$ 3,35 por galão. **

# Exercício exemplo
<b>Distinguindo entre um parâmetro e uma estatística</b><br>
Determine se o valor numérico descreve um parâmetro populacional ou uma estatística amostral. Explique seu raciocínio.
1. Uma pesquisa recente com aproximadamente 400.000 empregadores reportou que o salário médio inicial para um especialista em
marketing é de US$ 53.400 por ano. (Fonte: National Association of
Colleges and Employers.)

2. A nota média de matemática obtida no vestibular pelos calouros de
uma universidade é 514.

3. Em uma checagem aleatória de 400 lojas varejistas, o FDA (Food
and Drug Administration) descobriu que 34% das lojas não estavam
estocando peixes na temperatura apropriada.

<b>Solução</b><br>
1. Em razão de a média de US$ 53.400 por ano ser baseada em um
subconjunto da população, ela é uma estatística amostral.

2. Em razão de a nota média de matemática de 514 ser baseada em
todos os calouros, ela é um parâmetro populacional.

3. Em razão de o percentual (34%) ser baseado em um subconjunto da
população, ele é uma estatística amostral.

# Sua vez!
No ano passado, uma empresa com 65 funcionários teve um gasto
total de US$ 5.150.694 com salários. A quantia gasta descreve um parâmetro populacional ou uma estatística amostral?<br>
* a. Determine se a quantia gasta é de uma população ou uma amostra.
* b. Especifique se a quantia gasta é um parâmetro ou uma estatística.

**Sua resposta aqui!**


**Essa base é de uma população, pois a empresa possui 65 funcionários e nos mostra o total gasto com salários. A quantia gasta é um parâmetro, porque é o gasto total.**

# Classificando um conjunto de dados
Nos exercícios a seguir, determine se o conjunto de dados é uma
população ou amostra. Explique seu raciocínio.
11. A receita de cada uma das 30 companhias na média industrial do Dow Jones.

12. A quantidade de energia acumulada por cada turbina
de vento em um campo eólico.

13. Uma pesquisa com 500 espectadores em um estádio
com 42.000 espectadores.

14. O salário anual de cada farmacêutico em uma farmácia.

15. Os níveis de colesterol de 20 pacientes em um hospital
com 100 pacientes.

16. O número de televisores em cada residência nos Estados Unidos.

17. O resultado final de cada jogador de golfe em um torneio.

18. A idade de cada terceira pessoa que entra em uma loja
de roupas.

19. O partido político de cada presidente americano.

20. Os níveis de contaminação do solo em 10 localidades
próximas a um aterro

**Sua resposta aqui!**

11. É uma base do tipo população
12. É uma base do tipo população
13. É uma base do tipo Amostra, pois a pesquisa contém 500 espectadores, mas o total(população) contém 42.000 espectadores.
14. É uma base do tipo população
15.  É uma base do tipo Amostra, pois a pesquisa contém 20 pacientes, mas o total(população) contém 100 pacientes.
16. É uma base do tipo população
17. É uma base do tipo população
18. É uma base do tipo amostra.
19. É uma base do tipo população
20. É uma base do tipo amostra
"""

