# -*- coding: utf-8 -*-
"""Dicionários.ipynb

Automatically generated by Colaboratory.


# **Dicionários**

---
"""

dic = {'nome':"Weber", 'idade':27, 'altura':1.81}
print(type(dic))

# Acessando chaves(atributos)
print(dic.keys())

# Acessando valores
print(dic.values())

# Acessando valor+chave
print(dic.items())

# Organizando as informações
print(f"O nome dele é {dic['nome']}, tem {dic['idade']} anos e mede {dic['altura']}m")

dir(dict)

help(dict)

"""# **>>> Exercícios**

---

1.   Crie um dicionário com, pelo menos, 3 chaves/valor (fácil)
"""

# Insira seu código aqui
dicionario = {'comida': 'arroz', 'cor': 'branco', 'tipo': '1'}
print(dicionario)

"""2.   Em uma nova célula remova 1 ítem chave/valor do dicionário criado anteriormente (médio)"""

# Insira seu código aqui
dicionario.pop('comida')
dicionario

"""3.   Crie um novo dicionário, armazenando-o em uma nova variável e agora unifique este com outro dicionário criado anteriormente (difícil)"""

# Insira seu código aqui
novo_dicionario = {"telefone": '966220-9292', "rg": '966220-9292', "cpf": '966220-9292'}
dicionario.update(novo_dicionario)
dicionario
