# -*- coding: utf-8 -*-
"""LaçosDeRepetição.ipynb

Automatically generated by Colaboratory.



# **>>> WHILE**

---
"""

# while
# ENQUANTO A DECLARAÇÃO FOR True, O BLOCO SERÁ EXECUTADO 

n = 0
while n <= 10:
  print(n)
  n = n+1  # n += 1

# +=, -=, *=, /= ...
n = 0
while n <= 10:
  print(n)
  n += 1

# while True realiza o código por tempo indeterminado: cuidado!
while True:
  print(0)

"""## **O break**

---
"""

# Com a instrução break podemos parar o loop mesmo se a condição while for verdadeira
n = 0
while n <= 10:
  print(n)
  if n == 3:
    break
  n = n+1

"""## **O continue**

---
"""

# Com a instrução continue podemos continuar a próxima iteração de forma ilimitada: cuidado!
n = 0
while n <= 10:
  print(n)
  if n == 3:
    continue
  n = n+1

"""# **>>> FOR**

---
"""

# ITERAÇÃO ATRAVÉS DE SEQUÊNCIAS (lista, tupla, dicionario, set, string)

pessoas = ['Ana', 'Maria', 'Alita']
for pessoa in pessoas:
  print(pessoa)

# ITERAÇÃO EM STRINGS

x = "Alita"
for letra in x:
  print(letra)

# ITERAÇÃO RANGE
for x in range(10):
  print(x)

# TAMBÉM PODE RECEBER "INICIO,FIM,PASSO"
for x in range(0,100,2):
  print(x)

# PODERÁ RECEBER ELSE
for x in range(10):
  print(x)
else:
  print("fim!")

# PODERÁ RECEBER break 
for x in range(10):
  print(x)
  if x == 5:
    print("fim!")
    break

# E continue
for x in range(10):
  print(x)
  if x == 5:
    print("fim!")
    continue

# Loops Aninhados
a = ['verde', 'roxa', 'amarela']
b = ['maçã', 'uva', 'banana']

for x in a:
  for y in b:
    print(x,y)

"""# **>>> Exercícios**

---

1.   Crie um algoritmo que solicite ao usuário 3 números e printe na tela a média destes (fácil)
"""

# Insira seu código aqui
print("Me dê 3 números e eu calcularei a média!")
num1 = int(input("Numero: "))
num2 = int(input("Numero: "))
num3 = int(input("Numero: "))
media = num1+num2+num3/3
print(f"A média desse número é {media}")

"""2.   Crie um algoritmo que solicite ao usuário um número e apresente o fatorial deste número como resultado (médio)
[Clique aqui para saber como calcular o fatorial.](https://pt.wikipedia.org/wiki/Fatorial)
"""

print("numero")
num = int(input("Numero: "))

fat = 1
contador = 0 
while (contador < num):
  contador = contador + 1
  fat = fat * contador 

print(f"O fatorial do número {num} é {fat}")

"""3.   Crie um algoritmo que solicite 5 números. Ao término, printar o maior e o menor número (difícil)"""

# Insira seu código aqui
print("cinco numeros")
num = int(input("Número: "))
num2 = int(input("Número: "))
num3 = int(input("Número: "))
num4 = int(input("Número: "))
num5 = int(input("Número: "))

numeros = [num, num2, num3, num4, num5]
numeros.sort()

print(numeros[0])
print(numeros[4])

"""## **>>> Solução**

---
"""

# Exercício 1
for x in range(1,2):
  a = int(input(f"Digite a 1º nota: "))
  b = int(input(f"Digite a 2º nota: "))
  c = int(input(f"Digite a 3º nota: "))
d = a+b+c
print(f"A média destes números é de {d/3:.2f}")

# Exercício 2
x = int(input("Digite um número inteiro: "))
f = 1
a = 2
while a <= x:
  f = f*a
  a += 1
print(f"O fatorial de {x} é {f}")

# Exercício 3
n1 = int(input("Digite o 1º número: "))
n2 = int(input("Digite o 2º número: "))
n3 = int(input("Digite o 3º número: "))
n4 = int(input("Digite o 4º número: "))
n5 = int(input("Digite o 5º número: "))
maior = n1
if n2>n1 and n2>n3 and n2>n4 and n2>n5:
  maior = n2
if n3>n1 and n3>n2 and n3>n4 and n3>n5:
  maior = n3
if n4>n1 and n4>n2 and n4>n3 and n4>n5:
  maior = n4
if n5>n1 and n5>n2 and n5>n3 and n5>n4:
  maior = n5
menor = n1
if n2<n1 and n2<n3 and n2<n4 and n2<n5:
  menor = n2
if n3<n1 and n3<n2 and n3<n4 and n3<n5:
  menor = n3
if n4<n1 and n4<n2 and n4<n3 and n4<n5:
  menor = n4
if n5<n1 and n5<n2 and n5<n3 and n5<n4:
  menor = n5
print(f"O maior número é o {maior} e o menor número é o {menor}")
