# -*- coding: utf-8 -*-
# """Fase3R.ipynb
# 
# Automatically generated by Colaboratory.
# 
# 
# # Seja ensinável e execute as tarefas compartilhadas. Por fins didáticos e para melhor separação mental das sintaxes Python/R, realizaremos todos os exercícios de Python em R.
# ![alt text](https://media0.giphy.com/media/pheOCmHVZehjy/source.gif)
# 
# ## Utilize apenas funções e pacotes R para os desafios abaixo
# #### Skills principais trabalhadas: tolerância a frustração, pesquisa, auto-didatismo, compreensão de texto, lógica de programação e leitura de documentação(pacotes).
# 
# Faça a leitura de um dataset(conjunto de dados) do Rbase e mostre as primeiras linhas deste dataset
# """
# 
# # INSIRA SEU CÓDIGO AQUI
library(datasets)
head(attitude)

# """Faça a leitura de um dataset(conjunto de dados) do Rbase e mostre as últimas linhas deste dataset"""
# 
# # INSIRA SEU CÓDIGO AQUI

library(datasets)
tail(attitude)


# 
# """Utilizando uma função Rbase, abra um dataset contido em sua própria máquina."""
# 
# # INSIRA SEU CÓDIGO AQUI

df <- read.csv("c://arquivo.csv", sep = ";")

# 
# """Crie uma função que recebe 2 parâmetros e retorna o maior valor destes."""
# 
# # INSIRA SEU CÓDIGO AQUI

print("Me dê dois números e irei verificar qual é o maior entre eles.")
num1 <- as.integer(readline("Número 1: "))
num2 <- as.integer(readline("Número 2: "))

if (num1 > num2){
  print(paste("O número ",num1,"é maior que o número", num2))}
elif{
  print(paste())
}



# 
# """Crie ou abra um dataset e na sequência, faça plotagem das features em um gráfico de barras."""
# 
# # INSIRA SEU CÓDIGO AQUI
library(ggplot2)
df <- read.csv("c://cohab.csv", sep = ";")
ggplot(diamonds, aes(x = cut)) +
  geom_bar()

# 
# """Com o dataset abaixo carregado, realize os exercícios seguintes:"""
# 
enderecos <- c("Rua Marcelino 851, São Paulo", "Avenida Voluntários da Pátria 367, Curitiba", "Rua do corcovado 198, Rio de janeiro")
produtos <- c("TV", "notebooks", "GPU", "mouses", "Teclado")
sentencas <- stringr::sentences[1:10]
campos <- c("order_number", "order_date", "customer_email", "product_title", "amount")
skills <- c("João Silva (jr)", "Rita Cadillac (senior)", "Chris Brown (senior)", "Sara Sarali (pleno)")
# 
# """Normalize o vetor de endereços substituindo letras maiúsculas por minúsculas."""
# 
# # INSIRA SEU CÓDIGO AQUI
library(stringr)
enderecos <- str_to_lower(enderecos)



# 
# """Puxe apenas a parte numérica do vetor de endereços."""
# 
# # INSIRA SEU CÓDIGO AQUI

library(stringr)
x <- as.numeric(str_extract_all(enderecos, "[0-9]+")[[1]])



# 
# """Divida o vetor de endereços em duas partes: endereço e cidade. O resultado deve ser uma matriz."""
# 
# # INSIRA SEU CÓDIGO AQUI
enderecos_df = data.frame(x = (enderecos))
a <- data.frame(do.call("rbind", strsplit(as.character(enderecos_df$x), ",", fixed = TRUE)))
#a <- matrix(enderecos, 3, 2)
colnames(a) <- c("Endereço", "Cidade")

result_1 <- strsplit(enderecos,",")[[1]][1:3]
result_2 <- strsplit(enderecos,",")[[2]][1:3]
result <- list(result_1,result_2)


# 
# """Normalize o vetor "produtos" removendo todos os espaços em branco desnecessários (início, meio e fim), capitalizando todas as letras."""
# 
# # INSIRA SEU CÓDIGO AQUI

implode <- function(..., sep=' ') {
  paste(..., collapse=sep)
}


implode(produtos)

