# -*- coding: utf-8 -*-
# """Fase2R.ipynb
# 
# Automatically generated by Colaboratory.
# 
# 
# # Seja ensinável e execute as tarefas compartilhadas. Por fins didáticos e para melhor separação mental das sintaxes Python/R, realizaremos todos os exercícios de Python em R.
# ![alt text](https://media.tenor.com/images/51e469036910eb2ece677863200af5a8/tenor.gif)
# 
# Crie um algoritmo em R que peça uma nota, entre 0 e 100. Mostre uma mensagem caso o valor seja inválido e continue pedindo até que o usuário informe um valor válido.
# """

# INSIRA SEU CÓDIGO AQUI
while (T){
  nota = readline("Por favor, insira um valor entre 0 e 100. Nota: \n")
  tryCatch({
    nota = as.integer(nota)
    if (nota > 0 && nota <= 100){
      break 
    }
  },
  warning=function(cond){}
  )
}

#"""Crie um algoritmo em R que leia um nome de usuário e a sua senha e não aceite a senha igual ao nome do usuário, mostrando uma mensagem de erro e voltando a pedir as informações.<br>"""

# INSIRA SEU CÓDIGO AQUI
print("_________Cadastro de usuário_________")
user = readline("Usuário: ")
senha = readline("Senha: ")

if (user == senha){
  print("Por favor, usuario e senha tem que ser diferente um do outro.")
}

# """Crie um algoritmo em R que leia e valide as seguintes informações:
# * Nome: maior que 3 caracteres;
# * Idade: entre 0 e 150;
# * Salário: maior que zero;
# * Sexo: 'f' ou 'm';
# * Estado Civil: 's', 'c', 'v', 'd';
# """

# INSIRA SEU CÓDIGO AQUI
while (T){
    nome = as.character(readline("Nome:"))
    idade = as.character(readline("Idade:"))
    salario = as.double(readline("Salário:"))
    sexo = as.character(readline("Sexo F/M:"))
    estado_civil = as.character(readline("Estado civil s - solteiro/c - casado/v - viúvo/d - divorciado:"))
    if (length(nome) < 3){
      print("Por favor, insira um nome com no mínimo 3 caracteres")
      return
    }
    break
  
}

#"""Supondo que a população de um país A seja da ordem de 80000 habitantes com uma taxa anual de crescimento de 3% e que a população de B seja 200000 habitantes com uma taxa de crescimento de 1.5%.<br><br> Crie um algoritmo em R que calcule e escreva o número de anos necessários para que a população do país A ultrapasse ou iguale a população do país B, mantidas as taxas de crescimento."""

# INSIRA SEU CÓDIGO AQUI

#"""Desenvolva um gerador de tabuada, capaz de gerar a tabuada de qualquer número inteiro entre 1 a 10. O usuário deve informar de qual numero ele deseja ver a tabuada. A saída deve ser conforme o exemplo abaixo:
# Tabuada de 5:<br>
# 5 X 1 = 5<br>
# 5 X 2 = 10<br>
# ...<br>
# 5 X 10 = 50<br>
# """

# INSIRA SEU CÓDIGO AQUI
num = as.integer(readline("Numero: "))

for (c in 1:10){
  calc = num * c
  print(paste("",num,"X",c,"=",calc))
}

#"""Crie um algoritmo em R que leia três números e mostre o maior e o menor deles."""

# INSIRA SEU CÓDIGO AQUI
lista <- vector()
for (c in 1:3){
  num = as.integer(readline(paste("Número" ,c,":")))
  lista[c] <- num
}
ordenado = sort(lista)
print(paste("O maior valor da lista é",ordenado[3],"e o menor valor é", ordenado[1]))

#"""Crie um algoritmo em R que peça 2 números, base e expoente, calcule e mostre o primeiro número elevado ao segundo número. Não utilize a função de potência da linguagem."""

# INSIRA SEU CÓDIGO AQUI
base = as.integer(readline("Base: "))
expoente = as.integer(readline("Expoente: "))
calc = base ** expoente

print(paste("",base, "elevado á",expoente,"=",calc))

#"""Crie um algoritmo em R que peça 10 números inteiros, calcule e mostre a quantidade de números pares e a quantidade de números impares."""

# INSIRA SEU CÓDIGO AQUI
lista_par = ""
lista_impar = ""
for (i in 1:10){
  num = as.integer(readline(paste("Numero {",i,"}: ")))
  if (num %% 2 == 0){
    lista_par = paste(lista_par, as.character(num))
  }
  else {
    lista_impar = paste(lista_impar, as.character(num))
  }
}

print(paste("Dos números que você inseriu os pares são: ",lista_par))
print(paste("e os ímpares são",lista_impar))

#"""Um funcionário de uma empresa recebe aumento salarial anualmente: Sabe-se que: Esse funcionário foi contratado em 1995, com salário inicial de R$ 1.000,00; Em 1996 recebeu aumento de 1,5% sobre seu salário inicial; A partir de 1997 (inclusive), os aumentos salariais sempre correspondem ao dobro do percentual do ano anterior. Crie um algoritmo em R que determine o salário atual desse funcionário. Após concluir isto, altere o programa permitindo que o usuário digite o salário inicial do funcionário"""

# INSIRA SEU CÓDIGO AQUI
library(tidyverse)
data <- c(Sys.Date())
datas <- as.Date(data, "%d/%m/%Y")
year = as.numeric(format(data, format = "%Y"))
ano_contr = as.integer(readline("Em que ano você foi contratado? "))
calc_year = year - ano_contr
salario = as.double(readline("Quanto você ganhava quando foi contratado?"))
perc_aument = 0.015
aumento = salario * perc_aument


for (c in 1:calc_year){
  salario = salario + aumento
  aumento = aumento * 2
  print(aumento)
}

print(paste("Salário final", salario))

#"""Crie um algoritmo em R com uma função que necessite de um argumento. A função retorna o valor de caractere ‘P’, se seu argumento for positivo, e ‘N’, se seu argumento for zero ou negativo."""

# INSIRA SEU CÓDIGO AQUI
num = as.integer(readline("Número: "))
if (num > 0){
  print("P")
  }else{
  print("N")
  }

#"""Construa uma função que receba uma data no formato DD/MM/AAAA e devolva uma string no formato D de mesPorExtenso de AAAA. Opcionalmente, valide a data e retorne NULL caso a data seja inválida."""

# INSIRA SEU CÓDIGO AQUI
library(tidyverse)

df <- data.frame(stringsAsFactors = FALSE, dates = c(readline("Data: ")))

data_sep <- df %>% separate(dates, c("day", "month", "year"), sep = "/")

mes <- c('Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro')

print(paste(data_sep$day,"/",mes[as.numeric(data_sep$month)],"/",data_sep$year))