# -*- coding: utf-8 -*-
# """R.ipynb
# 
# Automatically generated by Colaboratory.
# 
# 
# 
# # R
# R é um software estatístico/linguagem de programação muito utilizado no campo acadêmico. Domina-lo é requisito essencial para Cientistas de Dados e carreiras adjuntas a esta pois através dele podemos manipular dados, visualiza-los e ainda construir modelos preditivos(I.A), além de poder ainda construir diversas aplicações com o R Markdown(sites, livros online, formulários…).
# 
# ---
# 
# Vantagens R:
# + Open-Source: gratuito e com comunidade cada vez maior e mais ativa;
# + Com uma grande comunidade por conta do fenômeno Open Source, surgem milhares de bibliotecas gratuitas para uso;
# + Multi-plataforma: Windows, Mac, Linux…
# + Já falamos que é requisito para a “profissão mais sexy do século” ?<br>
# 
# ![Ranking das Linguagens de Programação e suas aplicações do IEE SPECTRUM
# ](https://secureservercdn.net/198.71.233.197/o9y.9a5.myftpupload.com/wp-content/uploads/ranking-linguagens.png)<br>
# Ranking das Linguagens de Programação e suas aplicações do IEE SPECTRUM 2018
# 
# ## Ambiente de Desenvolvimento
# + RSTUDIO: https://www.rstudio.com/products/rstudio/download/
# + R: https://cloud.r-project.org/
# + Anaconda: https://www.anaconda.com/distribution/
# 
# ---
# 
# Para aumento de produtividade, indicamos o uso das 4 telas no R STUDIO, acessando: <b>View > Panes > Show All Panes</b>
# ![alt text](https://secureservercdn.net/198.71.233.197/o9y.9a5.myftpupload.com/wp-content/uploads/tela-rstudio2-1024x432.png)
# 
# ---
# 
# Para execução de R no google colab, acesse: https://colab.research.google.com/notebook#create=true&language=r
# 
# Para maiores informações acesse https://blog.qoda.com.br/r-em-1-semana-parte-1-de-7/
# """

x = 3
x

# """## Conceitos básicos
# <b>Declarando variáveis, comentando código e printando na tela:</b>
# 
# + Declare variáveis com = ou <-
# + Utilize # para comentar linhas
# + Utilize print() para executar na tela
# + Utilize readline(prompt=”…”) para receber texto(inputs)
# """

x = "Hello Qoda!"
y <- "Hello Qoda!"
z = readline("Qual é o seu nome?")

# Print na tela seu primeiro programa em R!
print(x) #retorna Hello Qoda!
print(y) #retorna Hello Qoda!
# z solicitará ao usuário o seu nome e ao preencher armazenará na variável "z".

z

# """## Dados e Operadores
# 3.1 Tipos de Dados(básicos)
# 
# + Character(“Texto”)
# Neste tipo inserimos caracteres, podendo ser números, textos, símbolos…;
# + Integer (1L)
# Integer se refere a números inteiros e utilizamos o “L” para determina-lo, diferente do Numeric, onde os números são decimais: 1.0 e não 1;
# + Numeric (7.25)
# Números decimais, mesmo que declarando-os como 12, o sistema retornará 12.0, por exemplo.
# + Logical (T/F ou TRUE/FALSE)
# Tipo de dado com retorno TRUE ou FALSE, assim como T ou F. TRUE quando atendidas as condições e FALSE quando não atendidas. Nos aprofundaremos logo logo neste tipo de dado: tenha paciência.
# """

caract = "Texto caractere"
class(caract)

inteiro = 15L
class(inteiro)

num = 15
class(num)

logic = TRUE
class(logic)

# """## Operadores
# 
# 
# >OPERADOR | OPERAÇÃO
# >--- | ---
# >+ | Adição
# >- | Subtração
# >* | Multiplicação
# >/ | Divisão
# >^ ou ** | Exponenciação
# >%% | Módulo
# >%/% | Divisão inteiros
# """

100+100

100-10

100*2

3^2

10%%3 #retorna sobra da divisão

10%/%3 # retorna parte inteira da divisão

#"""## Estruturas de dados

### Vetor
# """
# 
vec = 3
 is.vector(vec) #Retorna TRUE
# 
# # Para adicionar diversos elementos em 1 vetor, use c()
vec = c(1,2,3,"texto")
class(vec) #retorna character pois todos elementos serão do mesmo tipo
# 
# """### Lista (elementos de tipos diferentes)"""

x = c("texto1","texto2")
y =  c(1,2,3)
z = c(T,F,T)
lista = c(x,y,z) 
lista

#"""### MATRIZ (todos elementos serão do mesmo tipo)"""

mat = matrix(c(1,2),nrow=1,ncol=2,byrow = TRUE) 
mat

#"""### DATAFRAME (estrutura para armazenar em forma de tabela)"""

x = data.frame(nome = c("Ana","Weber","Aquiles"),
               idade = c(24L,27L,2L),
               salario = c(12000,0,0))
nrow(x) # retorna número de linhas do dataframe
ncol(x) # retorna número de colunas do dataframe
dim(x) # retorna número de linhas e colunas
print(x)

# """## Condicionais
# Quando você estiver “qodando”, é importante inserir algumas regras em seu código para que a máquina saiba O QUE fazer, QUANDO fazer e COMO fazer. Assim sendo, temos a figura das CONDICIONAIS, ferramentas essenciais, uma vez que queremos a ação executada apenas se certa condição for atendida. Um exemplo: você sai com guarda-chuva SE acredita que pode chover. Assim sendo você possui 1 condicional para levar o guarda chuva.
# 
# ### <b>Operadores lógicos</b>
# 
# >OPERADOR | LÓGICA
# >--- | ---
# >< | Menor
# >> | Maior
# ><= | Menor ou igual
# >>= | Maior ou igual
# >== | Igual
# >!= | Diferente
# >! | Not(negação)
# """

3 > 0

0 == 0

"a" == 1

# """### <b>if()</b>
# 
# if (condicao) {
#  
#     comandos executados quando TRUE
#  
# }
# """

a = 1
b = 100
if (a<b) {
 
    print("A é menor que B")
 
}

# """### <b>if else()</b>
# 
# if (condicao) {
#  
#   comandos executados quando TRUE
#  
# } else {
#  
#     comandos executados quando FALSE
#  
# }
# """

a = as.integer(readline("Digite um número para A: "))
b = as.integer(readline("Digite outro número, para B: "))
if (a<b) {
 
    print("A é menor que B")
 
} else {
  print("A é maior que B")
}

# """### <b>ifelse()</b>
# 
# ifelse(condição,"retorno se TRUE","retorno se FALSE")
# """

a = as.integer(readline("Digite um número para A: "))
b = as.integer(readline("Digite outro número, para B: "))

ifelse(a>b,"A maior que B","A menor que B")

# """### Desafio condicionais em R
# Crie um chatbot simples que pergunte ao usuário sua idade. 
# + Caso sua idade esteja compreendida entre 18 anos ou menos, retorne: você é uma criança!
# + Caso sua idade esteja compreendida entre 19  e 50 anos, retorne: você é um adulto!
# + Caso sua idade esteja compreendida entre 51 anos ou mais, retorne: você é um adulto experiente!
# """

#Digite seu código aqui 
idade = as.integer(readline("Qual a sua idade? "))
if (idade <= 18) {
  print("Você é uma criança!")
}
if (idade > 19 && idade <= 50){
  print("Você é um adulto!")
}
if (idade >= 51){
  print("Você é um adulto experiente!")
}

# """## Laços de repetição(loops)
# While e For
# """

# WHILE SINTAXE
while(condição) {
  comandos
}

# WHILE NA PRÁTICA
z <- 100
while(z <= 200) {
  print(z)
  z <- z + 1
}

# FOR SINTAXE
for (x in y) {
  comandos
}

# FOR NA PRÁTICA
for (x in 1:100) {
  print(x)
}

# """## Funções
# Funções nada mais são do que blocos de código “encapsulados” onde você armazena uma lista de instruções e posteriormente, utilizando o nome da função em seu código, você a chama para execução inserindo alguns parâmetros se necessário.
# 
# Temos as funções “R base”, ou seja, aquelas que já são carregadas de forma nativa junto ao R como a função “mean()” que calcula a média, por exemplo, entre outras diversas:
# """

# FUNÇÕES R BASE
x = c(1,2,3,4,5,6,7,8,9,10)

sd(x) #desvio padrão

mean(x) #média

head(iris) #primeiras linhas dataframe

tail(iris) #ultimas linhas dataframe

file.choose() #abre pasta para caminho de arquivos, utilize no RSTUDIO!

# """### Criação de funções
# Podemos criar nossas próprias funções em R de forma simples e intuitiva.
# """

porcentagem <- function(num, por) {
  num <- as.integer(readline(prompt="Digite o número para cálculo: "))
  por <- as.integer(readline(prompt="Agora digite a porcentagem que gostaria de descobrir deste número: "))
  return(num * por/100)
}
porcentagem()

# """##### Criamos uma função chamada “porcentagem”. Nela inserimos 2 parâmetros para funcionamento: “num”, que se refere ao número alvo, e “por”, referente a porcentagem a ser calculada. Desta forma utilizamos o “readline()” para pedir os números ao usuário e ao término lhe entregar o calculo de sua porcentagem. Por fim, apenas executamos a função e ela começa a interagir com o usuário.
# 
# ## Pacotes
# Pacotes nada mais são que códigos prontos de terceiros, criados para solucionar problemas específicos ao implementar novas funções ao seu código R. Temos pacotes para Machine Learning, Matemática, Web Scraping, Desenvolvimento Web e outros milhares e aqui está o grande trunfo do movimento Open-Source: produção de pacotes em massa.
# 
# 
# ---
# 
# 
# <b>Onde encontrar pacotes? há 3 formas, via RStudio:</b>
# 
# 1. CRAN
# Via linha de comando no próprio console RStudio com:
# install.packages(“nome-do-pacote”,dependencies=TRUE)
# 
# 2. Manualmente, no CRAN formato .zip ou .tar.gz;
# no menu do Rstudio selecione Menu Tools > Install Packages > Install packages from pacage arquive file e selecione o pacote escolhido.
# 
# 3. No R Studio, na tela 4, em “Packages”: busque, selecione e clique em “install”.
# """

#Instala pacote
install.packages("ggplot2", dependencies=TRUE)

# Carrega pacote para ser utilizado no código
library(ggplot2)

# """### Tidyverse
# Conjunto de pacotes focados em análise de dados
# """

install.packages("tidyverse") 

# instalará: 
#✔ ggplot2 (gráficos)
#✔ purrr (programação funcional)
#✔ tibble (criação dataframes)
#✔ dplyr (manipulação de dataframes)
#✔ tidyr (transformação de dataframes)
#✔ stringr (lida com strings e regex)
#✔ readr (leitura dados retangulares: csv, tsv...)  
#✔ forcats (lida com fatores) fatores são estruturas de dados utilizadas para ordenar strings

# """### GGPLOT2
# https://github.com/rstudio/cheatsheets/blob/master/data-visualization-2.1.pdf
# >TIPO | OBJETO
# >--- | ---
# >Dispersão (scatterplot) | geom_point()
# >Gráfico de bolhas | geom_point()
# >Histograma | geom_histogram()
# >Boxplot | geom_boxplot()
# >Densidade | geom_density()
# >Gráfico de linhas | geom_line()
# """

# Listando todos datasets do R base
data(package = .packages(all.available = TRUE))
# ou apenas data()

ggplot(data = <DATA>) + 
  <GEOM_FUNCTION>(
     mapping = aes(<MAPPINGS>),
     stat = <STAT>, 
     position = <POSITION>
  ) +
  <COORDINATE_FUNCTION> +
  <FACET_FUNCTION> # dividir o gráfico em subplots

# SCATTERPLOT ou gráfico de dispersão
library(tidyverse)
#displ: o tamanho do motor de um carro, em litros.
#hwy: a eficiência de combustível de um carro na estrada, em milhas por galão (mpg). 
ggplot(data = mpg) + geom_point(mapping = aes(x = displ, y = hwy))

mpg

# GRÁFICO DE BARRAS
ggplot(diamonds, aes(x = cut)) +
  geom_bar()

# """###TIBBLE
# Tibbles são como dataframes, entretanto, apresentam melhorias de produtividade.
# 
# ###DPLYR
# https://github.com/rstudio/cheatsheets/blob/master/data-transformation.pdf
# Pacote mais utilizado para transformação de dados.<br>
# Funções principais:
# > Função | Objetivo
# >--- | ---
# >filter() | filtra linhas
# >select() | seleciona colunas
# >mutate() | cria/modifica colunas
# >arrange() | ordena a base
# >summarise() | sumariza a base
# """

library(dplyr)
mtcars %>%
  filter(mpg > 20)

mtcars %>% 
  select(mpg)

mtcars %>% 
  mutate(
    economy = ifelse(mpg>20,"CARRO ECONÔMICO","CARRO BEBERRÃO")
  ) %>%
  select(mpg, economy)

mtcars %>% 
  arrange(mpg) %>%
  select(everything())

mtcars %>% 
  summarise(media_mpg = median(mpg, na.rm=TRUE))

# """###TIDYR
# funções principais: gather() e spread()
# """

library(tibble)
library(tidyr)

df <- tibble(w = 1, x = 2, y = 3)
z = gather(df, "variavel", "valor")

df

z

z2 = spread(z, "variavel","valor")
z2

#"""###STRINGR"""

library(stringr)
texto = "Este é um texto para simples conferência de caracteres."
str_length(texto)

str_to_upper(texto)

s1 = "Minha idade é"
s2 = " "
s3 = "59 anos."
str_c(s1,s2,s3)

# """###READR
# Realiza leitura de dados nos formatos .txt, .csv, .fwf e .log, 10x mais veloz que os comandos usuais. Não há necessidade de converter caracteres em fatores(stringAsFactors = FALSE)
# https://rawgit.com/rstudio/cheatsheets/master/data-import.pdf
# """

# library(readr)
# read_delim(), read_csv(), read_tsv(), read_csv2()
# read_fwf(), read_table()
# read_log()
# read_file() ## lê um arquivo em uma *string*.

# """## Pipe %>%
# 
# 
# ---
# 
# O operador %>% (pipe) veio para tornar a leitura de códigos mais legível/compreensível. Foi introduzido junto ao pacote magrittr e já existem outros pacotes criados para sua utilização
# 
# De inicio, vamos instalar e carregar o magrittr:
# """

install.packages("magrittr")
library(magrittr)

funcao(a, b)  # sem pipe
a %>% f(b) # operador pipe

a <- c(1, 2, 3, 4)
sqrt(sum(a))

a %>% sum() %>% sqrt()